@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'PO Supplier address'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity ZMM_APP17_SUPADD as select from I_Supplier as Sup
inner join I_Address_2 as ADD on ADD.AddressID = Sup.AddressID 
                                and ADD.Region = Sup.Region
{
   key Sup.Supplier,
   key ADD.AddressID,
   Sup.SupplierAccountGroup,
   Sup.SupplierName,
   Sup.BusinessPartnerName1,
   Sup.BusinessPartnerName2,
   Sup.BusinessPartnerName3,
   Sup.BusinessPartnerName4,
   Sup.BPAddrCityName,
   Sup.BPAddrStreetName,
   Sup.AddressSearchTerm1,
   Sup.AddressSearchTerm2,
   Sup.BPSupplierFullName,
//   sup.DistrictName,
   Sup.TaxNumber3,
   Sup.CityName,
   Sup.PostalCode,
   Sup.StreetName,
   Sup.Region,
   concat(Sup.StreetName,concat( ADD.StreetPrefixName1,ADD.StreetPrefixName2)) as ADDRESS1,
   concat(Sup.CityName,concat('PIN - ',Sup.PostalCode)) as cipin,
   Sup.PhoneNumber2 as phone,    
//   ADD.StreetPrefixName1,
//   ADD.StreetPrefixName2,
//   ADD.StreetSuffixName1,
//   ADD.StreetSuffixName2,
//   ADD.DistrictName
//   Add.AddressID,
   ADD.AddressPersonID,
   ADD.AddressRepresentationCode,
   ADD.AddressObjectType,
   ADD.CorrespondenceLanguage,
   ADD.PrfrdCommMediumType,
   ADD.AddresseeFullName,
   ADD.PersonGivenName,
   ADD.PersonFamilyName,
   ADD.OrganizationName1,
   ADD.OrganizationName2,
   ADD.OrganizationName3,
   ADD.OrganizationName4,
   ADD.AddressSearchTerm1 as AddressSearchTerm1a,
   ADD.AddressSearchTerm2 as AddressSearchTerm2a,
   ADD.CityNumber,
   ADD.CityName as CityName1,
   ADD.DistrictName,
   ADD.VillageName,
   ADD.PostalCode as PostalCodea,
   ADD.CompanyPostalCode,
   ADD.Street,
   ADD.StreetName as StreetNamea,
   ADD.StreetAddrNonDeliverableReason,
   ADD.StreetPrefixName1,
   ADD.StreetPrefixName2,
   ADD.StreetSuffixName1,
   ADD.StreetSuffixName2,
   ADD.HouseNumber,
   ADD.HouseNumberSupplementText,
   ADD.Building,
   ADD.Floor,
   ADD.RoomNumber,
   ADD.Country,
   ADD.Region as Region1,
   ADD.FormOfAddress,
   ADD.TaxJurisdiction,
   ADD.TransportZone,
   ADD.POBox,
   ADD.POBoxAddrNonDeliverableReason,
   ADD.POBoxIsWithoutNumber,
   ADD.POBoxPostalCode,
   ADD.POBoxLobbyName,
   ADD.POBoxDeviatingCityName,
   ADD.POBoxDeviatingCityCode,
   ADD.POBoxDeviatingRegion,
   ADD.POBoxDeviatingCountry,
   ADD.CareOfName,
   ADD.DeliveryServiceTypeCode,
   ADD.DeliveryServiceNumber,
   ADD.AddressTimeZone,
   ADD.SecondaryRegion,
   ADD.SecondaryRegionName,
   ADD.TertiaryRegion,
   ADD.TertiaryRegionName,
   ADD.RegionalStructureCheckStatus,
   ADD.AddressGroup,
   ADD.DistrictNumber,
   ADD.Village,
   ADD.RegionalStructureGroup,
   ADD.AddressCreatedByUser,
   ADD.AddressCreatedOnDateTime,
   ADD.AddressChangedByUser,
   ADD.AddressChangedOnDateTime,
   ADD._AddressGroup,
   ADD._AddressObjectType,
   ADD._AddressPersonName,
   ADD._AddressRepresentationCode,
   ADD._CorrespondenceLanguage,
   ADD._Country,
   ADD._CurrentDfltEmailAddress,
   ADD._CurrentDfltFaxNumber,
   ADD._CurrentDfltLandlinePhoneNmbr,
   ADD._CurrentDfltMobilePhoneNumber,
   ADD._DeliveryServiceTypeCode,
   ADD._EmailAddress,
   ADD._FaxNumber,
   ADD._FormOfAddress,
   ADD._MainWebsiteURL,
   ADD._OrganizationAddress,
   ADD._PersonAddress,
   ADD._PhoneNumber,
   ADD._POBoxAddrNonDeliverableReason,
   ADD._POBoxDeviatingCityCode,
   ADD._POBoxDeviatingCountry,
   ADD._POBoxDeviatingRegion,
   ADD._PostalCity,
   ADD._PrfrdCommMediumType,
   ADD._Region,
   ADD._RegionalStructureCheckStatus,
   ADD._SecondaryRegion,
   ADD._Street,
   ADD._StreetAddrNonDeliverableRsn,
   ADD._TertiaryRegion,
   ADD._TimeZone,
   ADD._TransportationZone,
   ADD._UniformResourceIdentifier   

}
