@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Purchase Order Plant Address'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity ZMM_APP18_PLANTADD
  as select from I_Plant     as PL
    inner join   I_Address_2 as ad on ad.AddressID = PL.AddressID
{
  key ad.AddressID,
  key ad.AddressPersonID,
  key ad.AddressRepresentationCode,
  key PL.Plant,
      ad.AddressObjectType,
      ad.CorrespondenceLanguage,
      ad.PrfrdCommMediumType,
      ad.AddresseeFullName,
      ad.PersonGivenName,
      ad.PersonFamilyName,
      ad.OrganizationName1,
      ad.OrganizationName2,
      ad.OrganizationName3,
      ad.OrganizationName4,
      ad.AddressSearchTerm1,
      ad.AddressSearchTerm2,
      ad.CityNumber,
      ad.CityName,
      ad.DistrictName,
      ad.VillageName,
      ad.PostalCode,
      ad.CompanyPostalCode,
      ad.Street,
      ad.StreetName,
      ad.StreetAddrNonDeliverableReason,
      ad.StreetPrefixName1,
      ad.StreetPrefixName2,
      ad.StreetSuffixName1,
      ad.StreetSuffixName2,
      ad.HouseNumber,
      ad.HouseNumberSupplementText,
      ad.Building,
      ad.Floor,
      ad.RoomNumber,
      ad.Country,
      ad.Region,
      ad.FormOfAddress,
      ad.TaxJurisdiction,
      ad.TransportZone,
      ad.POBox,
      ad.POBoxAddrNonDeliverableReason,
      ad.POBoxIsWithoutNumber,
      ad.POBoxPostalCode,
      ad.POBoxLobbyName,
      ad.POBoxDeviatingCityName,
      ad.POBoxDeviatingCityCode,
      ad.POBoxDeviatingRegion,
      ad.POBoxDeviatingCountry,
      ad.CareOfName,
      ad.DeliveryServiceTypeCode,
      ad.DeliveryServiceNumber,
      ad.AddressTimeZone,
      ad.SecondaryRegion,
      ad.SecondaryRegionName,
      ad.TertiaryRegion,
      ad.TertiaryRegionName,
      ad.RegionalStructureCheckStatus,
      ad.AddressGroup,
      ad.DistrictNumber,
      ad.Village,
      ad.RegionalStructureGroup,
      ad.AddressCreatedByUser,
      ad.AddressCreatedOnDateTime,
      ad.AddressChangedByUser,
      ad.AddressChangedOnDateTime,
      PL.PlantName,
      PL.ValuationArea,
      PL.PlantCustomer,
      PL.PlantSupplier,
      PL.FactoryCalendar,
      PL.DefaultPurchasingOrganization,
      PL.SalesOrganization,

      PL.PlantCategory,
      PL.DistributionChannel,
      PL.Division,
      PL.Language,
      PL.IsMarkedForArchiving,
      PL.BusinessPlace,
      PL._Customer.TaxNumber3       as gstin,
      ad._EmailAddress.EmailAddress as emailid,
      ad._EmailAddress.EmailAddressIsCurrentDefault
}
