CLASS zbp_sd_app06_rv DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zsd_app06_rv.
PUBLIC SECTION.
CLASS-DATA : gt_salesgateout  TYPE TABLE OF zsd_app02_tb3.
ENDCLASS.



CLASS ZBP_SD_APP06_RV IMPLEMENTATION.
ENDCLASS.
