CLASS zbp_mm_app01_rv1 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zmm_app01_rv1.
  PUBLIC SECTION.
    CLASS-DATA:gt_app01_tb3 TYPE TABLE OF zmm_app01_tb3.
ENDCLASS.



CLASS ZBP_MM_APP01_RV1 IMPLEMENTATION.
ENDCLASS.
