CLASS zbp_mm_app01_rcv DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zmm_app01_rcv.
  PUBLIC SECTION.
    CLASS-DATA:gt_app01_tb1 TYPE TABLE OF zmm_app01_tb1,
               gt_app01_tb2 TYPE TABLE OF zmm_app01_tb2.
*

ENDCLASS.



CLASS ZBP_MM_APP01_RCV IMPLEMENTATION.
ENDCLASS.
