CLASS zcl_autoenroll_buffer DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    CLASS-DATA:
      gt_header TYPE STANDARD TABLE OF zi_autoenroll WITH EMPTY KEY,

      gt_child  TYPE STANDARD TABLE OF zcv_autoenroll WITH EMPTY KEY.

*  PROTECTED SECTION.
*  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_AUTOENROLL_BUFFER IMPLEMENTATION.
ENDCLASS.
