@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Product Plant Active Core Entity'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity ZI_ProductPlantCusVH1
  as select from I_ProductPlantStdVH    as mat
    inner join   I_ProductDescription_2 as desc on  desc.Product  = mat.Product
                                                and desc.Language = 'E'
  //  association [1..1] to I_Plant as _Plant on _Plant.Plant = mat.Plant
{
      @Search: {defaultSearchElement: true, ranking: #MEDIUM, fuzzinessThreshold: 0.8}
  key mat.Product,
      @Search: {defaultSearchElement: true, ranking: #HIGH, fuzzinessThreshold: 0.8}
      //      @ObjectModel.foreignKey.association: '_Plant'
      desc.ProductDescription
      //      _Plant.Plant as plant,
      //      _Plant
      //    CountryOfOrigin,
      //    RegionOfOrigin,
      //    ProductionInvtryManagedLoc,
      //    ProfileCode,
      //    ProfileValidityStartDate,
      //    AvailabilityCheckType,
      //    FiscalYearVariant,
      //    PeriodType,
      //    ProfitCenter,
      //    GoodsReceiptDuration,
      //    MaintenanceStatusName,
      //    IsMarkedForDeletion,
      //    MRPType,
      //    MRPResponsible,
      //    ABCIndicator,
      //    MinimumLotSizeQuantity,
      //    MaximumLotSizeQuantity,
      //    FixedLotSizeQuantity,
      //    ConsumptionTaxCtrlCode,
      //    IsCoProduct,
      //    ConfigurableProduct,
      //    StockDeterminationGroup,
      //    HasPostToInspectionStock,
      //    IsBatchManagementRequired,
      //    SerialNumberProfile,
      //    IsNegativeStockAllowed,
      //    HasConsignmentCtrl,
      //    IsPurgAcrossPurgGroup,
      //    IsInternalBatchManaged,
      //    ProductCFOPCategory,
      //    ProductIsExciseTaxRelevant,
      //    UnderDelivToleranceLimit,
      //    OverDelivToleranceLimit,

      //    SpecialProcurementType,
      //    ProductionSchedulingProfile,
      //    ProductionSupervisor,
      //    SafetyStockQuantity,
      //    GoodsIssueUnit,
      //    SourceOfSupplyCategory,
      //    ConsumptionReferenceProduct,
      //    ConsumptionReferencePlant,
      //    ConsumptionRefUsageEndDate,
      //    ConsumptionQtyMultiplier,
      //    ProductUnitGroup,
      //    DistrCntrDistributionProfile,
      //    ConsignmentControl,
      //    GoodIssueProcessingDays,
      //    PlannedDeliveryDurationInDays,
      //    ProductIsCriticalPrt,
      //    ProductLogisticsHandlingGroup,
      //    MaterialFreightGroup,
      //    OriginalBatchReferenceMaterial,
      //    OriglBatchManagementIsRequired,
      //    ProductConfiguration,
      //    ProductMinControlTemperature,
      //    ProductMaxControlTemperature,
      //    ProductControlTemperatureUnit,
      //    ValuationCategory,
      //    BaseUnit,
      //    ItemUniqueIdentifierIsRelevant,
      //    ItemUniqueIdentifierType,
      //    ExtAllocOfItmUnqIdtIsRelevant,
      //    /* Associations */
      //    _ABCIndicator,
      //    _ABCIndicatorDesc,
      //    _CFOPDesc,
      //    _ConfigurableProduct,
      //    _ConfigurableProductName,
      //    _CountryOfOriginText,
      //    _DistributionProfile,
      //    _DistributionProfileText,
      //    _FiscalYearVariant,
      //    _FiscalYearVariantDescription,
      //    _GoodsIssueUnit,
      //    _GoodsMovementQuantity,
      //    _MaterialLotSizingProcedure,
      //    _MaterialStock,
      //    _MRPController,
      //    _MRPType,
      //    _PeriodType,
      //    _PeriodTypeText,

      //    _PlantESPP,
      //    _PlantProcurement,
      //    _PlantQualityMgmt,
      //    _PlantSales,
      //    _ProdControlTemperatureUnit,
      //    _ProdCtrlTemperatureUnitText,
      //    _ProdPlantInternationalTrade,

      //    _ProductCFOPCategory,
      //    _ProductFreightGroup,
      //    _ProductFreightGroupText,
      //    _ProductPlantCosting,
      //    _ProductPlantForecast,
      //    _ProductStatus,
      //    _ProductStatusText,
      //    _ProductStorageLocation,
      //    _PurchasingGroup,
      //    _RegionText,
      //    _Site,
      //    _SourceOfSupplyCategory,
      //    _Stock,
      //    _StockDeterminationGroup,
      //    _StockDeterminationGroupT,
      //    _Text,
      //    _UnitOfMeasureText
}
