CLASS zbp_mm_app06_rv DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zmm_app06_rv.
  PUBLIC SECTION.
    CLASS-DATA: gt_bdgcode TYPE TABLE OF zmm_app06_tb1.
ENDCLASS.



CLASS ZBP_MM_APP06_RV IMPLEMENTATION.
ENDCLASS.
